In [17]:
#Libraries 

import warnings; warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import nltk
import spacy
# Text processing
import re
from nltk.corpus import stopwords
from bs4 import BeautifulSoup
import contractions

In [5]:
#Retrieve the dataset without having to import the dataset again

%store -r disneyland_df

In [7]:
disneyland_df

,Review_ID,Rating,Year_Month,Reviewer_Location,Review_Text,Branch
0,670772142,4,2019-4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong
1,670682799,4,2019-5,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong
2,670623270,4,2019-4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong
3,670607911,4,2019-4,Australia,HK Disneyland is a great compact park. Unfortu...,Disneyland_HongKong
4,670607296,4,2019-4,United Kingdom,"the location is not in the city, took around 1...",Disneyland_HongKong
...,...,...,...,...,...,...
42651,1765031,5,missing,United Kingdom,i went to disneyland paris in july 03 and thou...,Disneyland_Paris
42652,1659553,5,missing,Canada,2 adults and 1 child of 11 visited Disneyland ...,Disneyland_Paris
42653,1645894,5,missing,South Africa,My eleven year old daughter and myself went to...,Disneyland_Paris
42654,1618637,4,missing,United States,"This hotel, part of the Disneyland Paris compl...",Disneyland_Paris
42655,1536786,4,missing,United Kingdom,"I went to the Disneyparis resort, in 1996, wit...",Disneyland_Paris

In [19]:
def clean_text_total(text):
    """
    Clean raw text by removing noise.
    
    Steps:
        1. Remove HTML tags (e.g., <p>, <div>, <br>)
        2. Remove URLs (http://, https://, www.)
        3. Remove email addresses
        4. Normalize whitespace (multiple spaces → single space)
    
    Parameters:
        text (str): Raw text string
    
    Returns:
        str: Cleaned text string
    
    Example:
        >>> clean_text("<p>Visit http://example.com or email test@mail.com</p>")
        'Visit or email'
    """
    # Handle missing values
    if pd.isna(text):
        return ""
    
    # Convert to string
    text = str(text)
    
    # Step 1: Remove HTML tags
    # Pattern: <anything> where anything doesn't contain >
    text = re.sub(r'<[^>]+>', '', text)
    
    # Step 2: Remove URLs
    # Pattern: http(s):// or www. followed by non-whitespace
    text = re.sub(r'http\S+|www\.\S+', '', text)
    
    # Step 3: Remove email addresses
    # Pattern: something@something.something
    text = re.sub(r'\S+@\S+', '', text)

    #Step 4: Catch any additional HTML that didn't make it through the initial cleaning steps.
    text= BeautifulSoup(text, "html.parser").get_text()
    
    # Step 4: Normalize whitespace
    # Replace multiple spaces/tabs/newlines with single space
    text = re.sub(r'\s+', ' ', text).strip()

    # Step 5: Expand contractions
    text=contractions.fix(text)

    #Removes Special Characters
    text=re.sub(r'[^a-zA-Z0-9. !?]', ' ', text)
    
    return text

#This function is for the analysis on words themselves instead of as a whole
def remove_punctuation(text):
    text=re.sub(r'[^a-zA-Z0-9 ]', ' ', text)
    return text

In [21]:
disneyland_df['review_cleaned']=disneyland_df['Review_Text'].apply(clean_text_total)

In [25]:
nltk.download('stopwords') #need to download this pre-trained data for using with word tokenizer
#
stop_words_nltk = list(stopwords.words('english')) #define English as the stop words

#Create a new column to store the cleaned text
disneyland_df['clean_review_wo_stopwords']=disneyland_df['review_cleaned'].copy()

#Go through each review and remove any stopwords that exist.
for review in range(0, len(disneyland_df)):
    a = disneyland_df.clean_review_wo_stopwords[review].split()
    sentence=[ x for x in a  if x.casefold() not in stop_words_nltk]
    disneyland_df['clean_review_wo_stopwords'][review]=" ".join(sentence)

custom_stopwords = ['disneyland','disney','park','day','time','went','also','really','just']

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ysass\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [26]:
disneyland_df

,Review_ID,Rating,Year_Month,Reviewer_Location,Review_Text,Branch,review_cleaned,clean_review_wo_stopwords
0,670772142,4,2019-4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong,If you have ever been to Disneyland anywhere y...,ever Disneyland anywhere find Disneyland Hong ...
1,670682799,4,2019-5,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong,Its been a while since d last time we visit HK...,since last time visit HK Disneyland .. Yet tim...
2,670623270,4,2019-4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong,Thanks God it wasn t too hot or too humid when...,Thanks God hot humid visiting park otherwise w...
3,670607911,4,2019-4,Australia,HK Disneyland is a great compact park. Unfortu...,Disneyland_HongKong,HK Disneyland is a great compact park. Unfortu...,HK Disneyland great compact park. Unfortunatel...
4,670607296,4,2019-4,United Kingdom,"the location is not in the city, took around 1...",Disneyland_HongKong,the location is not in the city took around 1...,location city took around 1 hour Kowlon kids l...
...,...,...,...,...,...,...,...,...
42651,1765031,5,missing,United Kingdom,i went to disneyland paris in july 03 and thou...,Disneyland_Paris,i went to disneyland paris in july 03 and thou...,went disneyland paris july 03 thought brillian...
42652,1659553,5,missing,Canada,2 adults and 1 child of 11 visited Disneyland ...,Disneyland_Paris,2 adults and 1 child of 11 visited Disneyland ...,2 adults 1 child 11 visited Disneyland Paris b...
42653,1645894,5,missing,South Africa,My eleven year old daughter and myself went to...,Disneyland_Paris,My eleven year old daughter and myself went to...,eleven year old daughter went visit son London...
42654,1618637,4,missing,United States,"This hotel, part of the Disneyland Paris compl...",Disneyland_Paris,This hotel part of the Disneyland Paris compl...,hotel part Disneyland Paris complex wonderful ...
42655,1536786,4,missing,United Kingdom,"I went to the Disneyparis resort, in 1996, wit...",Disneyland_Paris,I went to the Disneyparis resort in 1996 wit...,went Disneyparis resort 1996 small child. minu...